title: Jan Olle Blog
email: janolle94@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jolle-ag.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_link: https://x.com/jolle_ag
github_link:  https://www.github.com/jolle-ag
linkedin_link: https://www.linkedin.com/in/jan-olle-aguilera

# Build settings
plugins:
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 1
  max_level: 1
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

feed:
  excerpt_only: true
  posts_limit: 500
  # collections:

kramdown:
  hard_wrap: true

future: true


highlighter: rouge

# Google analyitics id
# google_analytics:
#   id: G-JW9F0B7Y26 # fill in your Google Analytics ID


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - env
    - notebooks
    - venv
    - recipes

# collections:
#   recipes:
#     output: true
